
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "ilvermorny"
      image:
        repository: "docker.io/dagster/user-code-example"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/example_project/project/repo.py"
      port: 3030
