
global:
  serviceAccountName: "dagster"

dagster-user-deployments:
  enabled: true
  deployments:
    - name: "ilvermorny"
      image:
        repository: "us-central1-docker.pkg.dev/main-form-349700/dagster/dagster"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/project/repo.py"
      port: 3030
      envSecrets:
        - name: dagster-gcs-bucket-name
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

postgresql:
  enabled: false
  postgresqlHost: "10.99.0.3"
  postgresqlUsername: "postgres"
  postgresqlPassword: "SuperSafe"
  postgresqlDatabase: "dagster"

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envSecrets:
        - name: dagster-gcs-bucket-name
