
global:
  serviceAccountName: "dagster"

dagit:
  workspace:
    enabled: true
    servers:
      - host: "user-code-deployment-host-name"
        port: 3030
    envConfigMaps:
      - name: dagster-lea-vars
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
  nodeSelector:
    cloud.google.com/gke-spot: "true"

dagsterDaemon:
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"

dagster-user-deployments:
  enableSubchart: false

postgresql:
  enabled: false
  postgresqlHost: "10.0.0.0"
  postgresqlUsername: "postgres"
  postgresqlDatabase: "dagster"

generatePostgresqlPasswordSecret: false

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envConfigMaps:
        - name: dagster-lea-vars
      envSecrets:
        - name: dagster-edfi-api
      resources:
        limits:
          cpu: "250m"
          memory: "512Mi"
          ephemeral-storage: "1Gi"
        requests:
          cpu: "250m"
          memory: "512Mi"
          ephemeral-storage: "1Gi"
