
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "ilvermorny"
      image:
        repository: "us-central1-docker.pkg.dev/dagster-kubernetes/my-repository/dagster"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/example_project/project/repo.py"
      port: 3030
