
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "ilvermorny"
      image:
        repository: "us-central1-docker.pkg.dev/dagster-349517/dagster/dagster"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/project/repo.py"
      port: 3030
      env:
        GCS_BUCKET_NAME: "cool-bucket-name"
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envVars:
        - "GCS_BUCKET_NAME"
