
global:
  serviceAccountName: "dagster"

dagit:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 1Gi
  nodeSelector:
    cloud.google.com/gke-spot: "true"

dagsterDaemon:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 1Gi

dagster-user-deployments:
  enabled: true
  deployments:
    - name: "ilvermorny"
      image:
        repository: "us-central1-docker.pkg.dev/google-project-id/dagster/dagster"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/project/repo.py"
      port: 3030
      envSecrets:
        - name: dagster-gcs-bucket-name
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 512Mi

postgresql:
  enabled: false
  postgresqlHost: "10.0.0.0"
  postgresqlUsername: "postgres"
  postgresqlDatabase: "dagster"

generatePostgresqlPasswordSecret: false

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envSecrets:
        - name: dagster-gcs-bucket-name
